print("Welcome to the Band Name Generator.")
City = input("What's the name of the city you grew up in?\n")
Pet = input("What's your pet's name?\n")
print("Your band name could be {0} {1}".format(City,Pet))
print("K, Bye, Thanks!")